### ISSUE TITLE
Improve integrations codegen

### ISSUE THREAD

**Issue by daryllimyt** [TracecatHQ/tracecat#109]
# Motivation
The current implementation isn't type-exhaustive

# Benefits
- More type-exhaustive according to JSON Schema + OAS
- Instead of going `pydantic -> zod`, decoupling into an intermediate step to `pydantic -> intermediate -> zod` unlocks a lot of use cases:
  - Allows compiling integrations directly from public OpenAPI specs
  - Opens up future possibility of compiling integrations from other languages (though this would require generic/containerized runtimes)
- Offload codegen logic

# Possible solutions
## Using a common language agnostic spec
Convert from pydantic --> some spec --> zod.

### Options
> Pydantic -> OpenAPI
- https://docs.pydantic.dev/latest/concepts/json_schema/ `Model.model_json_schema()` is OAS compliant
- ~There exists well supported lib: https://docs.pydantic.dev/latest/integrations/datamodel_code_generator/~ (this is for OpenAPI -> pydantic)
> OpenAPI -> Zod
- https://zod.dev/?id=x-to-zod
- https://github.com/astahmer/openapi-zod-client

**Comment by topher-lo** [comment]
Resolved by massive Temporal rewrite: https://github.com/TracecatHQ/tracecat/pull/146
