### ISSUE TITLE
CORS issue on API endpoint.

### ISSUE THREAD

**Issue by lockness-Ko** [TracecatHQ/tracecat#118]
**Describe the bug**
API does not support the OPTIONS method which Chrome uses for CORS hints and the API does not send CORS headers which prevents Chrome from requesting the resource.

**To Reproduce**
1. Login to tracecat.
2. Navigate to /workflows.
3. Check console.

**Expected behavior**
Requests to the API from the browser are successful.

**Screenshots**
![image](https://github.com/TracecatHQ/tracecat/assets/42625905/e09ec28c-d0c0-4036-9a97-1c269c38f177)
![image](https://github.com/TracecatHQ/tracecat/assets/42625905/7cab7f2f-57d8-4c98-b98a-9346504d3e3e)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 123.0.6312.124

**Additional context**
Problem fixed by putting nginx with this config infront of the API:

```conf
location / {
        if ($request_method = OPTIONS ) {
                add_header Access-Control-Allow-Origin * always;
                add_header "Access-Control-Allow-Methods" "DELETE, POST, GET, OPTIONS";
                add_header "Access-Control-Allow-Headers" "Content-Type, Authorization";
                return 200;
        }
        add_header Access-Control-Allow-Origin * always;
        add_header "Access-Control-Allow-Methods" "DELETE, POST, GET, OPTIONS";
        add_header "Access-Control-Allow-Headers" "Content-Type, Authorization";
        proxy_pass http://localhost:8008/;
}
```

**Comment by topher-lo** [comment]
This should be fixable on the `app` side via the FastAPI `CORSMiddleware`. Will open an PR to fix this 👍

**Comment by topher-lo** [comment]
@lockness-Ko this is gold. Will add the fix today.

**Comment by topher-lo** [comment]
@lockness-Ko Turns out this is a RabbitMQ CORS issue...we are removing it in the beta version (i.e. temporal rewrite).

Will close as it as scheduled for removal next week.

**Comment by topher-lo** [comment]
@daryllimyt gg rabbitmq
