### ISSUE TITLE
Suggestion for this task - Bring-your-own LLM (OpenAI, Mistral, Anthropic etc.)

### ISSUE THREAD

**Issue by Greatz08** [TracecatHQ/tracecat#132]
There is one great open source project on GitHub called LiteLLM.
https://github.com/BerriAI/litellm

If that project is integrated to this project then this task of todo check list can be easily fulfilled without struggling and read documentations for n numbers of different LLM's as LiteLLM has simple schema/structure in which people can fill info  and use any LLM(100's of LLM supported by LiteLLM) easily.
It created local proxy server and use open ai api structure for working so we don't need too much things and don't have to study different LLM documentation to integrate it in this solution so things will be much more easy so I would suggest you to study on it and implement it to make things much more easy for yourself and for users too :-))
Many great projects have implemented and in some i have given this same suggestion so it can be helpful for all :-))
Thankyou for this great project

**Comment by topher-lo** [comment]
We evaluated a bunch of options (including the one you suggested), leaning towards https://github.com/Portkey-AI/gateway

Thoughts? @HakaishinShwet

**Comment by Greatz08** [comment]
Sorry for late response , it is also good @topher-lo  but i havent tested it out personally and have just seen repo so if you are satisfied with it then it's best for this solution :-)) Thanks for sharing this one i will try myself too and there is btw litellm discord server where you can ask them questions and differences and they will be best guys to resolve any doubts or queries you may in choosing between litellm and portkey gateway

**Comment by kevinr-security** [comment]
As long as their is support for your own LLM, i.e. hosted on something like Azure OpenAI or AWS Bedrock.

**Comment by topher-lo** [comment]
Closed by https://github.com/TracecatHQ/tracecat/pull/415

We now support all open source models via Ollama, OpenAI GPT models.

Please open PRs for other APIs / models not like supported (e.g. AWS Bedrock). We have plans to support Azure OpenAI via Outlines: https://dottxt-ai.github.io/outlines/latest/reference/models/openai/#azure-openai-models

**Comment by topher-lo** [comment]
One more note: litellm and berriai and portkey are all really useful looking technologies, but they are also too heavy for the what we need right now (i.e. the ability to call different models).

It's also too early to tell which of these "unified API" providers will win out in the end and we also want full control over the latest API features for Traceact's preferred LLM model for cybersec specific tasks.
