### ISSUE TITLE
Webhook support get request method

### ISSUE THREAD

**Issue by jarvis2f** [TracecatHQ/tracecat#14]
Hello, this is a great project, but I found some possible issues while using it today.
I saw that the configuration of the webhook supports get requests, but the request failed.

Maybe it's a problem here：
https://github.com/TracecatHQ/tracecat/blob/6431a85a60ab2f90279eec4ddbc19efda4063d60/tracecat/runner/app.py#L203

And maybe the content-type can be arbitrary and the payload can be empty?

**Comment by daryllimyt** [comment]
Hey! Thanks for raising this - we are aware the UI suggests that we currently support both POST and GET, but atm we only support POST. We definitely want to add support for GETs for webhooks soon though.

**Comment by topher-lo** [comment]
I'll take this on for the v0.0.1 release.

**Comment by topher-lo** [comment]
Resolved by https://github.com/TracecatHQ/tracecat/blob/deffd2926e1e719c93f777a3e361522efdcf3241/tracecat/api/app.py#L260-L265
