### ISSUE TITLE
not able to login after fresh installation of tracecat

### ISSUE THREAD

**Issue by kishanecosmob** [TracecatHQ/tracecat#147]
After installing tracecat getting the below error

Unhandled Runtime Error
Error: Error creating new user
![Screenshot from 2024-05-29 15-09-39](https://github.com/TracecatHQ/tracecat/assets/96779259/c7fdc796-31de-4e41-87e3-faffd5eca605)

Below are the logs files from docker.
 ○ Compiling /_error ...
 ✓ Compiled /_error in 1661ms
Start new user flow
Auth is disabled, using test token.
 ⨯ Error: Error creating new user
    at newUserFlow (/app/.next/server/chunks/[root of the server]__62c00d._.js:736:23)
Start new user flow
Auth is disabled, using test token.
 ⨯ Error: Error creating new user
    at newUserFlow (/app/.next/server/chunks/[root of the server]__62c00d._.js:736:23)

Call Stack
newUserFlow
/app/.next/server/chunks/[root of the server]__62c00d._.js (736:23)
process.processTicksAndRejections
node:internal/process/task_queues (95:5)
async
/app/node_modules/.pnpm/next@14.1.1_@babel+core@7.24.5_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (39:406)
async t2
/app/node_modules/.pnpm/next@14.1.1_@babel+core@7.24.5_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (38:6412)
async rS
/app/node_modules/.pnpm/next@14.1.1_@babel+core@7.24.5_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (41:1369)
async doRender
/app/node_modules/.pnpm/next@14.1.1_@babel+core@7.24.5_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js (1395:30)
async cacheEntry.responseCache.get.routeKind
/app/node_modules/.pnpm/next@14.1.1_@babel+core@7.24.5_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js (1544:40)
async DevServer.renderToResponseWithComponentsImpl
/app/node_modules/.pnpm/next@14.1.1_@babel+core@7.24.5_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js (1464:28)
async DevServer.renderPageComponent
/app/node_modules/.pnpm/next@14.1.1_@babel+core@7.24.5_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js (1861:24)
async DevServer.renderToResponseImpl
/app/node_modules/.pnpm/next@14.1.1_@babel+core@7.24.5_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js (1899:32)
async DevServer.pipeImpl
/app/node_modules/.pnpm/next@14.1.1_@babel+core@7.24.5_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js (912:25)
async NextNodeServer.handleCatchallRenderRequest
/app/node_modules/.pnpm/next@14.1.1_@babel+core@7.24.5_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js (269:17)
async DevServer.handleRequestImpl
/app/node_modules/.pnpm/next@14.1.1_@babel+core@7.24.5_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js (808:17)
async
/app/node_modules/.pnpm/next@14.1.1_@babel+core@7.24.5_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/dev/next-dev-server.js (331:20)
async Span.traceAsyncFn
/app/node_modules/.pnpm/next@14.1.1_@babel+core@7.24.5_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/trace/trace.js (151:20)
async DevServer.handleRequest
/app/node_modules/.pnpm/next@14.1.1_@babel+core@7.24.5_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/dev/next-dev-server.js (328:24)
async invokeRender
/app/node_modules/.pnpm/next@14.1.1_@babel+core@7.24.5_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js (136:21)
async handleRequest
/app/node_modules/.pnpm/next@14.1.1_@babel+core@7.24.5_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js (315:24)
async requestHandlerImpl
/app/node_modules/.pnpm/next@14.1.1_@babel+core@7.24.5_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js (339:13)
async Server.requestListener
/app/node_modules/.pnpm/next@14.1.1_@babel+core@7.24.5_babel-plugin-macros@3.1.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/start-server.js (140:13)

**Comment by topher-lo** [comment]
Could you kindly share:
1. Docker logs from the API service
2. Details about your environment and OS

Thanks!

**Comment by kishanecosmob** [comment]
1. attached docker api log file for your reference.
2. OS - NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
3. 2vCPU - 4GB of RAM
4. Installed one local VM in host machine

**Comment by daryllimyt** [comment]
Please follow this [section](https://docs.tracecat.com/installation#linux-users) in the docs, thanks! Also, please make sure that your installing one of the tagged releases.

**Comment by kishanecosmob** [comment]
- Attached my docker-compose.yaml for your reference.
- Same issues not resolved you.
- Provide more information and resolution steps so that I will explore tracecat.
Thanks

**Comment by topher-lo** [comment]
Your `.docx` file violates our security policy 😞

**Comment by kishanecosmob** [comment]
[dcoker-compose-file.pdf](https://github.com/TracecatHQ/tracecat/files/15492272/dcoker-compose-file.pdf)
i have attached .pdf file for docker-compose.yaml
