### ISSUE TITLE
Zombied action leds to wrong (completed) workflow run state

### ISSUE THREAD

**Issue by jarvis2f** [TracecatHQ/tracecat#16]
**Describe the bug**

Hello, I created a workflow with four actions to be executed sequentially. When the third action takes a long time to complete, the fourth action is not executed, and the logs simply output Workflow completed.

The reason seems to be that the current action was removed from running_jobs_store before the next action was added to ready_jobs_queue.

I'd like to ask when the scheduled execution feature will be supported, as I saw it in the documentation but couldn't find it on the configuration page.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by daryllimyt** [comment]
Hey, thanks for raising this! what were the 4 nodes + their inputs? if you can DM me your workflow ID (/workflows/{workflow_id}) I can try to reproduce this on my side.

Regarding scheduled execution, we definitely want to support this soon. That said, we're currently focused on general UX/stability and adding AI capabilities in the very short term, @topher-lo   can probably chime in here

**Comment by topher-lo** [comment]
Yeah let's prioritise scheduling. Our docs are one step ahead of us this time 😆. Give us the next few days?

I'm interested in the part "previous step takes a long time to run", we need to dig into this and then figure out what other corner cases we need to be aware of (and deal with).

Thoughts? @jarvis2f

**Comment by topher-lo** [comment]
@daryllimyt what's happening here? Any initial ideas, know that your busy on another thread right now, but let's get ahead of this

> Regarding scheduled execution, we definitely want to support this soon. That said, we're currently focused on general UX/stability and adding AI capabilities in the very short term, @topher-lo can probably chime in here

**Comment by jarvis2f** [comment]
> Hey, thanks for raising this! what were the 4 nodes + their inputs? if you can DM me your workflow ID (/workflows/{workflow_id}) over discord I can try to reproduce this on my side, and also happy to help you debug this issue over a call.

Sorry, I run it locally, so I can't send you the workflow ID.

**Comment by jarvis2f** [comment]
> Daryl what's happening here? Any initial ideas, I know you are working on other thread right now.
> 
> > Regarding scheduled execution, we definitely want to support this soon. That said, we're currently focused on general UX/stability and adding AI capabilities in the very short term, @topher-lo can probably chime in here

I tried to fix this issue and it works locally, but I'm not sure if this is the exact reason.

https://github.com/jarvis2f/tracecat/commit/186074e9512690579bf61bb63d88749620e9eb0d

**Comment by topher-lo** [comment]
@jarvis2f You are our second self reported self hosted user. Thanks for pushing this.

~~Is there anyway we can help you debug this with higher velocity / fidelity than on GitHub issues?~~

I think Daryl knows what's going on now

**Comment by daryllimyt** [comment]
Okay, I have a few hypotheses of what's going on here but I'm struggling to reproduce this locally. Can you help me build a MRE so I can help?

**Comment by jarvis2f** [comment]
@daryllimyt  I tried to reproduce this phenomenon on your platform in the last run.
There are four actions here, but there are only three records in the log, which is the same as when I ran it locally.
The last three actions are piped through an HTTP request to pipedream, where custom code simulates time-consuming operations. The workflow: https://platform.tracecat.com/workflows/0236171d49fe48d4862256092648cdcf

<img width="940" alt="image" src="https://github.com/TracecatHQ/tracecat/assets/137974272/5bb39d7f-c1fe-4c32-88c9-ff4a04922575">


![image](https://github.com/TracecatHQ/tracecat/assets/137974272/a5a9a126-0766-4f45-8f3e-8fb28afdaaf2)

**Comment by daryllimyt** [comment]
So I managed to get this working on the platform with pipedream so I can't really pinpoint the exact bug:

https://github.com/TracecatHQ/tracecat/assets/5508348/158c81aa-9c5e-455b-97d3-3c1a06671686

The events get logged correctly in the workflow run panel and the backend events also correspond to this.

Regardless, I'm currently working to make the visibility around this issue (and related functionality) better with server pushed events, and we also plan on adding code execution nodes in the near future as well. 

I'll leave this issue open in case this bug resurfaces again.

**Comment by daryllimyt** [comment]
Closing this for now as no related issues have been observed
