### ISSUE TITLE
Unhandled Runtime Error Error: Error creating new user | After fresh installation

### ISSUE THREAD

**Issue by kishanecosmob** [TracecatHQ/tracecat#164]
Hi Team,

We are getting a login error after a fresh installation on Ubuntu 20.04.

Please find the attached logs for your reference. 
[tracecat-api error log.docx](https://github.com/user-attachments/files/15799456/tracecat-api.error.log.docx)

[tracecat-frontend error log - auth disable.docx](https://github.com/user-attachments/files/15799457/tracecat-frontend.error.log.-.auth.disable.docx)

[.env file.docx](https://github.com/user-attachments/files/15799455/default.env.file.docx)
![Screenshot from 2024-06-12 11-53-44](https://github.com/TracecatHQ/tracecat/assets/96779259/6e4cfd23-8982-48d4-85da-e70ae248fca1)

**Comment by topher-lo** [comment]
Please kindly refrain from uploading insecure file formats for debugging. This is in violation of community guidelines. Moreover, this issue does not align with issue reporting requirements
