### ISSUE TITLE
Permissions errors when ~/.tracecat folder is created by Docker (root)

### ISSUE THREAD

**Issue by topher-lo** [TracecatHQ/tracecat#20]
**Describe the bug**
 `PermissionError: [Errno 13] Permission denied: '/home/user/.tracecat/storage'` occurs when running `pytest` from local user, but the directory was initially created by Docker (root user) as a docker-compose volme.

**Suggested fix**
Dockerize tests. Just use docker compose across all dev (local, CICD) environments.

**Comment by topher-lo** [comment]
Related to #22

**Comment by daryllimyt** [comment]
Should be closed by #105
