### ISSUE TITLE
Secrets manager to support other auth types

### ISSUE THREAD

**Issue by daryllimyt** [TracecatHQ/tracecat#25]
# Motivation
Need to make secrets manager generic so that we can support other secrets types.

# Implementation
## Design
- `Secret` will still extend `Resource` (it will have owner_id, created_at, updated_at)
- Include fields: id, platform, encrypted_secret (encrypted json object/string)

## Scope
- [x] API keys (MVP)
- [ ] Tokens
- [ ] OAuth

## Todos
- [x] #32  
- [x] #36 

# Blocks
- External integrations that require secrets #27 

# Resources
- https://kubernetes.io/docs/concepts/configuration/secret/#secret-types

**Comment by topher-lo** [comment]
Coming to close for now. The current secrets manager supports KV pairs (akin to AWS Secrets Manager / Modal). This is flexible enough for most use-cases.
