### ISSUE TITLE
Fix punycode deprecation warning

### ISSUE THREAD

**Issue by daryllimyt** [TracecatHQ/tracecat#30]
# Description
`(node:19052) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.`

# Plausible causes
- Local node version being v21.7.1. Even numbers are LTS.

# Fix
Likely - Upgrade yarn / pnpm and lock the version in package.json

# Resources
https://github.com/yarnpkg/yarn/issues/9013

**Comment by AshutoshNanaware** [comment]
Hello @daryllimyt , I am working on this issue. Can you please assign it to me to avoid any conflicts?

**Comment by daryllimyt** [comment]
hey, thanks for taking a look at this - going to close this for now as the issue appears to have been fixed in recent versions of pnpm
