### ISSUE TITLE
[FEATURE IDEA] Action to join results from multiple branches

### ISSUE THREAD

**Issue by topher-lo** [TracecatHQ/tracecat#336]
**Is your feature request related to a problem? Please describe.**
I want some way to collect data from multiple branches (e.g. a diamond pattern).

**Describe the solution you'd like**
A `join` node that waits for all upstream tasks to complete before executing, collects all the output events (or perhaps deal with multiple switch cases).

**Describe alternatives you've considered**
A sidecar reference table / `TEMP.` namespace to add data per workflow run.

**Current workaround**
Use reshape and conditional expressions.

**Additional context**
Prior art
- Torq exit operator node: https://learn.torq.io/docs/workflow-output-parameters
<img width="1401" alt="JSON mode" src="https://github.com/user-attachments/assets/7360888f-6b3f-4396-81d4-28c85febc2bf">

**Comment by daryllimyt** [comment]
Can we close this now that we've implemented join strategy in #471? Or is this something we might want to support down the line?

**Comment by daryllimyt** [comment]
Closed by #471
