### ISSUE TITLE
Workflow status shows up as successful even though action fails

### ISSUE THREAD

**Issue by daryllimyt** [TracecatHQ/tracecat#37]
**Describe the bug**
Workflow status shows up as successful even though action fails. This is a known bug

**To Reproduce**
Run a workflow that fails on an action.

**Expected behavior**
Workflow should reflect the error

**Screenshots**
![Screenshot 2024-04-11 at 18 35 22](https://github.com/TracecatHQ/tracecat/assets/5508348/37b314a7-707f-42f4-beca-3aa111100e9c)

**Comment by topher-lo** [comment]
No longer relevant given temporal rewrite.
