### ISSUE TITLE
HTTP Request Timeout

### ISSUE THREAD

**Issue by noahabbott123** [TracecatHQ/tracecat#391]
**Is your feature request related to a problem? Please describe.**
Tried awhile ago to use Trace cat. Really liked the platform, but ran into one simple bug/missing feature that completely broke the experience for me. When making an HTTP request, especially to grab alerts from a program such as Elastic, the HTTP request can be quite long. There is no way to override the seemingly very short timeout period of the request. 

**Describe the solution you'd like**
In the JSON schema of an HTTP request, be able to modify the default timeout of the request.

**Comment by topher-lo** [comment]
Thanks for reporting this @noahabbott123! We've got an update underway. Should be out before the end of day. Wanted to ask which version of Tracecat you tried?

**Comment by ghost** [comment]
0.5.2. Which is really old now I see 😂. Thank you for looking into it though! I tried it out a few months ago when evaluating open-source SOARs for our team.

**Comment by topher-lo** [comment]
@noahabbott123 Done! And just in time for our 0.10.0 release in the next 30 minutes 🚀

**Comment by topher-lo** [comment]
> 0.5.2. Which is really old now I see 😂. Thank you for looking into it though! I tried it out a few months ago when evaluating open-source SOARs for our team.

Woah excited for you to see the new platform

**Comment by ghost** [comment]
fantastic! will you drop the commit here when you push the release? would love to see what changed.

**Comment by topher-lo** [comment]
Here it is: https://github.com/TracecatHQ/tracecat/commit/2cc31176a998be5c50f3d153f3c1de3f4cea66d0

Just waiting for CI to complete for QA and if it all passes. Will make the release

**Comment by topher-lo** [comment]
https://github.com/TracecatHQ/tracecat/blob/2cc31176a998be5c50f3d153f3c1de3f4cea66d0/tracecat/actions/core/http.py#L51

**Comment by topher-lo** [comment]
Closed by https://github.com/TracecatHQ/tracecat/releases/tag/0.10.0
