### ISSUE TITLE
Additional actions in itsm/jira

### ISSUE THREAD

**Issue by matter1-git** [TracecatHQ/tracecat#398]
**Describe the solution you'd like**
I want to be able to query Jira for issues containing a certain key, summary, description, assignee or other fields. There should be 2 actions:
1. **query_issues** ( query jira and returns a list of dicts which contain all or only a few fields from each issue)
2. **get_issue** (get jira issue by key with the ability to get only certain fields from it) 

**Describe alternatives you've considered**
The alternative is to do core/http actions and have a UDF

I can work on these actions and create a PR if everything is okay.

**Comment by topher-lo** [comment]
Hi @matter1-git, great suggestion. We are reworking the way we do integrations to make it easier to add new functions.

Would suggest waiting until our release next week before opening a PR!

It's going to be a hybrid of Tines (pure HTTP templates) and Tracecat Python UDFs.

But the goal is to allow much easier self serve. 🙏

**Comment by matter1-git** [comment]
Yes of course. I will come back with a comment here next week.

**Comment by topher-lo** [comment]
Depends on #404

**Comment by topher-lo** [comment]
@matter1-git we added a few examples of Jira integrations in Registry. https://github.com/TracecatHQ/tracecat/tree/main/registry/tracecat_registry/templates/jira

We're going to release registry in the next 2-3 weeks. But wanted to share a preview of the API design!

**Comment by matter1-git** [comment]
Thank you very much. Looking forward for it 😁

**Comment by topher-lo** [comment]
Should be closed by #404
