### ISSUE TITLE
Actions Registry tutorial is missing information

### ISSUE THREAD

**Issue by skrilab** [TracecatHQ/tracecat#558]
**Describe the bug**
Actions Registry tutorial is missing information and images in the documentation.
https://docs.tracecat.com/tutorials/3-actions-registry

**To Reproduce**

_**In the step 1 ([Check out the Actions Registry](https://docs.tracecat.com/tutorials/3-actions-registry#:~:text=Check%20out%20the%20Actions%20Registry)):**_
The screenshot is missing (there is no such file as /img/tutorials/actions-registry/actions-registry.png)

_**In the step 2 ([Clone existing Action Template](https://docs.tracecat.com/tutorials/3-actions-registry#:~:text=Clone%20existing%20Action%20Template)):**_
What is meant by 'clone the existing Search URL with VirusTotal action template' ? Is it 'new from template' ?

<img width="580" alt="image" src="https://github.com/user-attachments/assets/1adbdf28-35af-4694-bb09-f72d3af4f03d">

I would suggest that we add the screenshot in this step too.

_**In the step 3 ([Edit the new action](https://docs.tracecat.com/tutorials/3-actions-registry#:~:text=3-,Edit%20the%20new%20action,-Edit%20the%20action)):**_
The YAML code is missing.

_**In the step 6 ([Run the workflow](https://docs.tracecat.com/tutorials/3-actions-registry#:~:text=6-,Run%20the%20workflow,-Click%20on%20the)):**_
The text states:
`Click on the Run button to execute the workflow. The results will be the same as the previous tutorial.`
But will the result be the same as in the previous tutorial if this new action returns only a boolean?

**Comment by topher-lo** [comment]
Would you be willing to take this on? We are swamped with infrastructure and our AI features right now. My original plan was to find time to work on docs next month, but very open to contributors helping

**Comment by skrilab** [comment]
I would be willing to take this on. I will create the PR, and then we can review and discuss the proposed results together.
