### ISSUE TITLE
[FEATURE IDEA] Email HTML Implementation

### ISSUE THREAD

**Issue by captainJackDnaiel** [TracecatHQ/tracecat#559]
### The idea
Would be nice if the smtp action support HTML so we can send cleaner emails.

### The solution
I did it by updating the `core.send_email_smtp` registry (https://github.com/TracecatHQ/tracecat/blob/main/registry/tracecat_registry/base/core/email.py) :

```
    ...
    headers: dict[str, str] | None = None,
) -> EmailMessage:
    msg = EmailMessage()

    ### HTML Implementation ###
    if re.search(r"<!doctype html>|<html>", body, re.IGNORECASE):
        msg.set_content("This email requires an HTML viewer to display properly.")  # Fallback text
        msg.add_alternative(body, subtype="html")
    else:
        msg.set_content(body)
    ### HMTL Implementation ###

    msg["From"] = sender
    msg["To"] = recipients
    msg["Subject"] = subject
    ...
```
Using this you can add html to the body input.

**Comment by topher-lo** [comment]
Looks good. Seems easy enough to implement. Let me do that now. Have some time before Thanksgiving starts :P
