### ISSUE TITLE
Session expired

### ISSUE THREAD

**Issue by AdelEddarai** [TracecatHQ/tracecat#65]
when i sign in i get this error 
![Screenshot 2024-04-18 175357](https://github.com/TracecatHQ/tracecat/assets/96699224/6b464763-a8a2-4399-8a7e-8eb79e4533ed)

**Comment by daryllimyt** [comment]
Hey, could you try clearing your browser cookies if logging again doesn't work?

**Comment by daryllimyt** [comment]
Please create a reproducible example in the future, thanks
