### ISSUE TITLE
CrowdStrike Integration

### ISSUE THREAD

**Issue by freeload101** [TracecatHQ/tracecat#7]
You can start with my CS_BADGER it's API for CS's  Splunk uses MFA / persistent tokens. :

I know it's gross ... I want to rewrite it with PING auth but I suck with SAML in python

https://github.com/freeload101/SCRIPTS/blob/master/Bash/CS_BADGER/CS_BADGER.sh

**Comment by topher-lo** [comment]
Crazy. We got this exact request in a private channel just yesterday. Our thinking is: webhook / http request + MFA / push notifications should be a default feature in a "modern" SOAR, not something a user has to build themselves.

Join us on Discord (unless you are there already?). Would be great to get your input as we are building this.

**Comment by soulmini** [comment]
@topher-lo @daryllimyt   wanna to reach out to you how i can

**Comment by topher-lo** [comment]
Our roadmap for integrations: massive sprint mid April to mid March.

For anybody reading this.

This issue will be resolved within that period of time.

**Comment by topher-lo** [comment]
Wrote an integration in a private branch. Will release as part of beta v0.1.0

**Comment by topher-lo** [comment]
Added a Crowdstrike alerts fetcher. Will close for now. Any new more specific CS integration feature requests should open a new issue!
