### ISSUE TITLE
Usage outside of cybersecurity

### ISSUE THREAD

**Issue by impredicative** [TracecatHQ/tracecat#9]
Could this perhaps more generally have use outside of cybersecurity? If so, could you explain the general and specific use cases? Or there comparable general alternatives that are better suited for other uses?

Also, if you can enable the Discussions section of this repo, it will help to discuss this there.

**Comment by topher-lo** [comment]
Great question. This is something we'd like to explore, but we are focused  on and biased towards building the best damn security product right now. Will close this issue. Look forward to the discussion in Discussions!

**Comment by ssnkhan** [comment]
> Could this perhaps more generally have use outside of cybersecurity? If so, could you explain the general and specific use cases? Or there comparable general alternatives that are better suited for other uses?
> 
> Also, if you can enable the Discussions section of this repo, it will help to discuss this there.

You could also look into something like https://github.com/huginn/huginn, which has a number of non-cyber use cases.
