### ISSUE TITLE
Problems initializing the Supabase service (Could not extract the anonymous key from Supabase) Real error: supabase: command not found 

### ISSUE THREAD

**Issue by Ohmsnipe** [TracecatHQ/tracecat#93]
**Describe the bug**

I am Facing Problems while installation:

Initializing Supabase services...

Could not extract the anonymous key from Supabase.

When i Echo the output:
 output=$(supabase start 2>&1)

    echo "$output"

There comes an error:
[services.sh](javascript:void(0);): line 141: supabase: command not found

Do you have an Idea where supabase must be installed?
why does your youtube video to installation not face this issue?

My supabase .env variables look like:
NEXT_PUBLIC_APP_URL="http://localhost:3000"

NEXT_PUBLIC_SUPABASE_ANON_KEY=

NEXT_PUBLIC_SUPABASE_URL="http://host.docker.internal:54321"

**To Reproduce**

**Expected behavior**

No supabase error

**Screenshots**

not needed

**Desktop (please complete the following information):**
 - OS:  Linux ubuntu

**Comment by daryllimyt** [comment]
Hello, you will need the `supabase` CLI tool (get it [here](https://supabase.com/docs/guides/cli/getting-started)). Seems like this is missing from our docs, thanks for catching this. I've pushed a change that should close this but will leave this up for now.

**Comment by topher-lo** [comment]
Looks resolved. Will close for now
